syntax = "proto3";
package user.internal;

option go_package = "github.com/go-saas/kit/user/private/conf;conf";

import "conf/conf.proto";
import "blob/blob.proto";
import "authz/authz/def.proto";
import "idp/idp.proto";
import "stripe/stripe.proto";

message Bootstrap {
  conf.Data data = 2;
  conf.Security security=3;
  conf.Services services =4;
  UserConf user=5;
  conf.Logging logging=6;
  conf.Tracers tracing=7;
  conf.AppConfig app=8;
  conf.Dev dev=9;
  .stripe.Conf stripe=501;
}


message Admin{
  string username =1;
  string password=2;
}

message UserConf{
  // Minimum password score. [0-5]
  int32 password_score_min=1;
  Admin admin =2;
  string root_url=4;
  // default to 5m
  // default to 5m
  // default to 5m
  // default to 5m
  // default to 5m

  idp.Config idp=200;
}

