# Hot reload config for the 'user' microservice

[build]
  cmd = "go build -o ./tmp/main ./cmd/user"
  bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "yaml", "yml"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000 # tiempo en ms antes de recompilar tras cambios

[log]
  level = "info"